server:
  port: 9050
  servlet.context-path: /account

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/voltrix-account-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

stripe:
  api:
    key: sk_test_51TtmQmPGKqWFfbtWSOuWV4nMsLumxlA8GKoWt160cibnMXZV8QhereAwwTh4TUhEyAPxDXyKgkuwp0PITAcBujVY007UivVuYz
  webhook:
    secret: whsec_7531d6ebdf2f3e56e3bdc45f7e78cb5d0e729b8fd4bdb5ad40df900fcbf25858
    
