server:
  port: 9030
  servlet.context-path: /intelligence

spring:
  datasource:
    url: jdbc:postgresql://localhost:9010/voltrix-intelligence-db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  ai:
    model.chat: openai
    openai:
      api-key: ${OPENROUTER_API_KEY}
      base-url: https://openrouter.ai/api/v1
      chat:
        options:
          # model: nvidia/nemotron-3.5-lightning:free
          model: inclusionai/ling-3.0-flash-fin:free
          # model: nvidia/nemotron-3-ultra-550b-a55b:free
          # model: qwen/qwen3.8-27b:free
          # model: cohere/north-mini-code:free
          temperature: 0.2
      embedding:
        options:
          model: nvidia/nemotron-3-embed-1b:free
